// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGdyWfYIqg0iAx3kGIjQkkue1OQ3LLvhk',
    appId: '1:328779793810:web:55f80444ed831e956aad4b',
    messagingSenderId: '328779793810',
    projectId: 'insurancewebapp-7d311',
    authDomain: 'insurancewebapp-7d311.firebaseapp.com',
    storageBucket: 'insurancewebapp-7d311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArT4r2hWdq-Ib_U5Jr1tD6k6BqVUPZ1YM',
    appId: '1:328779793810:android:106aa0669fb05b3a6aad4b',
    messagingSenderId: '328779793810',
    projectId: 'insurancewebapp-7d311',
    storageBucket: 'insurancewebapp-7d311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERg_tGuc_oZVDZUripvffIsGnZKjrYUI',
    appId: '1:328779793810:ios:3e5073cb6a77e2286aad4b',
    messagingSenderId: '328779793810',
    projectId: 'insurancewebapp-7d311',
    storageBucket: 'insurancewebapp-7d311.appspot.com',
    iosClientId: '328779793810-peu24khd41ruf2lhcplp6tmttedvb5q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
